trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuation $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
